name: Build and Push Docker container

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GHCR 
      uses: docker/login-action@v1  
      with: 
        registry: ghcr.io 
        username: classBabacar
        password: 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
